Attempt to correct dyld: Symbol not found __ZN7nsDebug9AssertionEPKcS1_S1_i in VBoxXPCOM.dylib, similar to changes in r125944
svn:sync-xref-src-repo-rev: r125949